### ISSUE TITLE
Regular Calender Events

### ISSUE THREAD

**Issue by rhit-villencr** [avichaljadeja2002/omni-planner#5]
- [x]  Create Prototype (1 hr)
- [x]  Send Prototype to client for confirmation
- [x]  Implement in code (1.5 hr)
- [x]  Reviewed prototype with client (0.3 hrs)
- [x]  Implemented changes in code (2 hrs)
- [x]  Connected backend (1 hr)
- [ ] Review With Client

Currently, I have more than one app for regular calendar events (date & time) planning, Make it so that there is a Personal Planning + Calendar page.

**Comment by rhit-siahmasf** [comment]
Just a type at the end "... make _it_ so that...". I approve this story, otherwise!

**Comment by rhit-villencr** [comment]
> Just a type at the end "... make _it_ so that...". I approve this story, otherwise!

Change Made!
