### ISSUE TITLE
Health Trackers

### ISSUE THREAD

**Issue by rhit-villencr** [avichaljadeja2002/omni-planner#8]
- [x] Create Prototype (1 hr)
- [x] Send Prototype to client for confirmation
- [x] Implement in code (1 hr)
- [x] Reviewed prototype with client (0.3 hrs)
- [x] Implemented changes in code (2 hrs)
- [x] Connected backend (1 hr)
- [ ] Review With Client

Currently, I have my health trackers all over the place, some apps track completely different things in the broad category of “health trackers”, make it so that there is a single app that allows users to track a certain number of health fields (ie age, weight, resting heart rate, etc.) without much external effort.

**Comment by rhit-siahmasf** [comment]
I know I wrote this story, I apologize for the vagueness now that I am looking at it. Can we say something along the lines of having a certain number of health fields that most users would know / be able to fill out without much external effort (i.e. age, weight, resting heart rate, etc.)?

**Comment by hookmark91** [comment]
Now that I've looked at it, I see that I wrote this story, and I apologize for its ambiguity. Could we state that there should be a set amount of health fields (such as age, weight, resting heart rate[,](https://quirkburst.com/) etc.) that the majority of people would be able to fill out without much help?
